export const WIDGET_MATCH_CREATE_REQUEST = 'WIDGET_MATCH_CREATE_REQUEST'
export const WIDGET_MATCH_CREATE_SUCCESS = 'WIDGET_MATCH_CREATE_SUCCESS'
export const WIDGET_MATCH_CREATE_FAILURE = 'WIDGET_MATCH_CREATE_FAILURE'
