export const WIDGET_MATCH_CREATE_REQUEST = 'WIDGET_MATCH_CREATE_REQUEST'
export const WIDGET_MATCH_CREATE_SUCCESS = 'WIDGET_MATCH_CREATE_SUCCESS'
export const WIDGET_MATCH_CREATE_FAILURE = 'WIDGET_MATCH_CREATE_FAILURE'

export const WIDGET_MATCH_UPDATE_REQUEST = 'WIDGET_MATCH_UPDATE_REQUEST'
export const WIDGET_MATCH_UPDATE_SUCCESS = 'WIDGET_MATCH_UPDATE_SUCCESS'
export const WIDGET_MATCH_UPDATE_FAILURE = 'WIDGET_MATCH_UPDATE_FAILURE'

export const WIDGET_MATCH_DESTROY_REQUEST = 'WIDGET_MATCH_DESTROY_REQUEST'
export const WIDGET_MATCH_DESTROY_SUCCESS = 'WIDGET_MATCH_DESTROY_SUCCESS'
export const WIDGET_MATCH_DESTROY_FAILURE = 'WIDGET_MATCH_DESTROY_FAILURE'
