export const REQUEST_ASYNC_BLOCK_FETCH = 'REQUEST_ASYNC_BLOCK_FETCH'
export const SUCCESS_ASYNC_BLOCK_FETCH = 'SUCCESS_ASYNC_BLOCK_FETCH'
export const FAILURE_ASYNC_BLOCK_FETCH = 'FAILURE_ASYNC_BLOCK_FETCH'
