FROM node:latest
MAINTAINER Nossas <tech@nossas.org>

ENV NEW_RELIC_HOME=./src NODE_ENV=production NODE_MODULES_CACHE=false NPM_CONFIG_PRODUCTION=false PORT=5001
ENV API_URL=server.bonde.devel:3000 APP_DOMAIN=bonde.devel:5001 PAGARME_KEY=aaa GOOGLE_FONTS_API_KEY=aaa

RUN mkdir /code

WORKDIR /code
COPY package.json yarn.lock /code/
RUN yarn
COPY . /code

CMD ["yarn", "start"]

EXPOSE 5001 3030
