FROM node:7-alpine
MAINTAINER Nossas <tech@nossas.org>

ENV NEW_RELIC_HOME=./src NODE_ENV=production NODE_MODULES_CACHE=false NPM_CONFIG_PRODUCTION=false PORT=5001

RUN apk add --no-cache make gcc g++ python git
RUN mkdir /code

WORKDIR /code
COPY package.json /code/
RUN npm install
COPY . /code
RUN npm run build

CMD ["node", "-r", "babel-register", "./server"]

EXPOSE 5001 3030
