packages:
  # all packages in subdirs of packages/ and components/
  - '.'
  - '!./libs/editor'
  - '!./libs/diagram'
  - './libs/*'
  - '!./packages/example-client'
  - './packages/*'
  # exclude packages that are inside test/ directories
  - '!**/test/**'
