debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
#     [entryPoints.http.redirect]
#     entryPoint = "https"
#   [entryPoints.https]
#   address = ":443"
#   [entryPoints.https.tls]

[retry]
[api]
[ping]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "bonde.devel"
watch = true
exposedbydefault = false

#[consul]
#endpoint = "consul:8500"
#watch = true
#prefix = "traefik"

# https://docs.traefik.io/user-guide/docker-and-lets-encrypt/
# [acme]
# email = "your-email-here@my-awesome-app.org"
# storage = "acme.json"
# entryPoint = "https"
# onHostRule = true
# [acme.httpChallenge]
# entryPoint = "http"
