export { default as MobilizationTemplatesCreatePage } from './MobilizationTemplatesCreatePage'
export { default as MobilizationTemplatesListPage } from './MobilizationTemplatesListPage'
export { default as MobilizationTemplatesChoosePage } from './MobilizationTemplatesChoosePage'
export { default as MobilizationTemplatesChooseCustomListPage } from './MobilizationTemplatesChooseCustomListPage'
export { default as MobilizationTemplatesChooseGlobalListPage } from './MobilizationTemplatesChooseGlobalListPage'
