export { default as TemplateChoosePage } from './template-choose-page'
export { default as TemplateChooseGlobalPage } from './template-choose-global-page'
export { default as TemplateChooseCustomPage } from './template-choose-custom-page'
export { default as TemplateCreatePage } from './template-create-page'
export { default as TemplateListPage } from './template-list-page'
