heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elk:9200
    - http://elk:5601

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elk

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elk:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'