//
// Async Action Types
//
export const REQUEST_ASYNC_BLOCK_FETCH = 'REQUEST_ASYNC_BLOCK_FETCH'
export const SUCCESS_ASYNC_BLOCK_FETCH = 'SUCCESS_ASYNC_BLOCK_FETCH'
export const FAILURE_ASYNC_BLOCK_FETCH = 'FAILURE_ASYNC_BLOCK_FETCH'

export const REQUEST_ASYNC_BLOCK_CREATE = 'REQUEST_ASYNC_BLOCK_CREATE'
export const SUCCESS_ASYNC_BLOCK_CREATE = 'SUCCESS_ASYNC_BLOCK_CREATE'
export const FAILURE_ASYNC_BLOCK_CREATE = 'FAILURE_ASYNC_BLOCK_CREATE'

export const REQUEST_ASYNC_BLOCK_UPDATE = 'REQUEST_ASYNC_BLOCK_UPDATE'
export const SUCCESS_ASYNC_BLOCK_UPDATE = 'SUCCESS_ASYNC_BLOCK_UPDATE'
export const FAILURE_ASYNC_BLOCK_UPDATE = 'FAILURE_ASYNC_BLOCK_UPDATE'

export const REQUEST_ASYNC_BLOCK_SELECT = 'REQUEST_ASYNC_BLOCK_SELECT'
export const SUCCESS_ASYNC_BLOCK_SELECT = 'SUCCESS_ASYNC_BLOCK_SELECT'
export const FAILURE_ASYNC_BLOCK_SELECT = 'FAILURE_ASYNC_BLOCK_SELECT'

export const REQUEST_ASYNC_BLOCK_DESTROY = 'REQUEST_ASYNC_BLOCK_DESTROY'
export const SUCCESS_ASYNC_BLOCK_DESTROY = 'SUCCESS_ASYNC_BLOCK_DESTROY'
export const FAILURE_ASYNC_BLOCK_DESTROY = 'FAILURE_ASYNC_BLOCK_DESTROY'

export const REQUEST_ASYNC_BLOCK_MOVE_UP = 'REQUEST_ASYNC_BLOCK_MOVE_UP'
export const SUCCESS_ASYNC_BLOCK_MOVE_UP = 'SUCCESS_ASYNC_BLOCK_MOVE_UP'
export const FAILURE_ASYNC_BLOCK_MOVE_UP = 'FAILURE_ASYNC_BLOCK_MOVE_UP'

export const REQUEST_ASYNC_BLOCK_MOVE_DOWN = 'REQUEST_ASYNC_BLOCK_MOVE_DOWN'
export const SUCCESS_ASYNC_BLOCK_MOVE_DOWN = 'SUCCESS_ASYNC_BLOCK_MOVE_DOWN'
export const FAILURE_ASYNC_BLOCK_MOVE_DOWN = 'FAILURE_ASYNC_BLOCK_MOVE_DOWN'

//
// Sync Action Types
//
export const BLOCK_BACKGROUND_IMAGE_UPLOADING = 'BLOCK_BACKGROUND_IMAGE_UPLOADING'
export const BLOCK_BACKGROUND_IMAGE_UPLOADED = 'BLOCK_BACKGROUND_IMAGE_UPLOADED'
export const BLOCK_SELECTED_LAYOUT = 'BLOCK_SELECTED_LAYOUT'
export const BLOCK_EDITION_MODE = 'BLOCK_EDITION_MODE'
