export const inputStyle = {
  borderBottomColor: 'rgb(238, 238, 238)',
  borderBottomLeftRadius: '2px',
  borderBottomRightRadius: '2px',
  borderBottomStyle: 'solid',
  borderBottomWidth: '1px',
  borderImageOutset: '0',
  borderImageRepeat: 'stretch stretch',
  borderImageSlice: '100%',
  borderImageSource: 'none',
  borderImageWidth: '1',
  borderLeftColor: 'rgb(238, 238, 238)',
  borderLeftStyle: 'solid',
  borderLeftWidth: '1px',
  borderRightColor: 'rgb(238, 238, 238)',
  borderRightStyle: 'solid',
  borderRightWidth: '1px',
  borderTopColor: 'rgb(238, 238, 238)',
  borderTopLeftRadius: '2px',
  borderTopRightRadius: '2px',
  borderTopStyle: 'solid',
  borderTopWidth: '1px',
  boxSizing: 'bordeRbox',
  color: 'rgb(17, 17, 17)',
  display: 'block',
  fontFamily: '"Source Sans Pro", "Proxima Nova", sans-serif',
  fontSize: '16px',
  lineHeight: '20px',
  marginBottom: '0px',
  marginLeft: '0px',
  marginRight: '0px',
  marginTop: '0px',
  outlineColor: 'rgb(17, 17, 17)',
  outlineStyle: 'none',
  outlineWidth: '0px',
  paddingBottom: '16px',
  paddingLeft: '16px',
  paddingRight: '16px',
  paddingTop: '16px',
  width: '1116px',
  MozBorderBottomColors: 'none',
  MozBorderLeftColors: 'none',
  MozBorderRightColors: 'none',
  MozBorderTopColors: 'none'
}
