export const NAMESPACE = 'mobilizations'

export const REQUEST_FETCH = `${NAMESPACE}/REQUEST_FETCH`

export const SUCCESS_FETCH = `${NAMESPACE}/SUCCESS_FETCH`

export const FAILURE_FETCH = `${NAMESPACE}/FAILURE_FETCH`

export const REQUEST_FILTER = `${NAMESPACE}/REQUEST_FILTER`

export const SUCCESS_FILTER = `${NAMESPACE}/SUCCESS_FILTER`

export const FAILURE_FILTER = `${NAMESPACE}/FAILURE_FILTER`

export const SELECT = `${NAMESPACE}/SELECT`
