// Mobilization actions
export const REQUEST_EDIT_MOBILIZATION = 'REQUEST_EDIT_MOBILIZATION'
export const SUCCESS_EDIT_MOBILIZATION = 'SUCCESS_EDIT_MOBILIZATION'
export const FAILURE_EDIT_MOBILIZATION = 'FAILURE_EDIT_MOBILIZATION'
export const EDIT_MOBILIZATION = 'EDIT_MOBILIZATION'
export const ADD_MOBILIZATION = 'ADD_MOBILIZATION'

// Organizations actions
export const REQUEST_FETCH_ORGANIZATIONS = 'REQUEST_FETCH_ORGANIZATIONS'
export const SUCCESS_FETCH_ORGANIZATIONS = 'SUCCESS_FETCH_ORGANIZATIONS'
export const FAILURE_FETCH_ORGANIZATIONS = 'FAILURE_FETCH_ORGANIZATIONS'
