// Auth actions
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE'
export const AUTH_LOAD = 'AUTH_LOAD'
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS'
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL'

// Mobilization actions
export const REQUEST_FETCH_MOBILIZATIONS = 'REQUEST_FETCH_MOBILIZATIONS'
export const SUCCESS_FETCH_MOBILIZATIONS = 'SUCCESS_FETCH_MOBILIZATIONS'
export const FAILURE_FETCH_MOBILIZATIONS = 'FAILURE_FETCH_MOBILIZATIONS'
export const REQUEST_EDIT_MOBILIZATION = 'REQUEST_EDIT_MOBILIZATION'
export const SUCCESS_EDIT_MOBILIZATION = 'SUCCESS_EDIT_MOBILIZATION'
export const FAILURE_EDIT_MOBILIZATION = 'FAILURE_EDIT_MOBILIZATION'
export const EDIT_MOBILIZATION = 'EDIT_MOBILIZATION'
export const ADD_MOBILIZATION = 'ADD_MOBILIZATION'

// Widget actions
export const FETCH_WIDGETS = 'FETCH_WIDGETS'
export const EDIT_WIDGET = 'EDIT_WIDGET'

// Block actions
export const FETCH_BLOCKS = 'FETCH_BLOCKS'
export const EDIT_BLOCK = 'EDIT_BLOCK'
export const REMOVE_BLOCK = 'REMOVE_BLOCK'
export const MOVE_BLOCK_UP = 'MOVE_BLOCK_UP'
export const MOVE_BLOCK_DOWN = 'MOVE_BLOCK_DOWN'

// Form entries actions
export const ADD_FORM_ENTRY = 'ADD_FORM_ENTRY'

// Donation actions
export const FINISH_TRANSACTION = 'FINISH_TRANSACTION'
export const TRANSACTION_DONE = 'TRANSACTION_DONE'
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL'

// Organizations actions
export const REQUEST_FETCH_ORGANIZATIONS = 'REQUEST_FETCH_ORGANIZATIONS'
export const SUCCESS_FETCH_ORGANIZATIONS = 'SUCCESS_FETCH_ORGANIZATIONS'
export const FAILURE_FETCH_ORGANIZATIONS = 'FAILURE_FETCH_ORGANIZATIONS'
