// Mobilization actions
export const REQUEST_FETCH_MOBILIZATIONS = 'REQUEST_FETCH_MOBILIZATIONS'
export const SUCCESS_FETCH_MOBILIZATIONS = 'SUCCESS_FETCH_MOBILIZATIONS'
export const FAILURE_FETCH_MOBILIZATIONS = 'FAILURE_FETCH_MOBILIZATIONS'
export const REQUEST_EDIT_MOBILIZATION = 'REQUEST_EDIT_MOBILIZATION'
export const SUCCESS_EDIT_MOBILIZATION = 'SUCCESS_EDIT_MOBILIZATION'
export const FAILURE_EDIT_MOBILIZATION = 'FAILURE_EDIT_MOBILIZATION'
export const EDIT_MOBILIZATION = 'EDIT_MOBILIZATION'
export const ADD_MOBILIZATION = 'ADD_MOBILIZATION'

// Widget actions
export const FETCH_WIDGETS = 'FETCH_WIDGETS'

// Form entries actions
export const ADD_FORM_ENTRY = 'ADD_FORM_ENTRY'

// Donation actions
export const FINISH_TRANSACTION = 'FINISH_TRANSACTION'
export const TRANSACTION_DONE = 'TRANSACTION_DONE'
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL'

// Organizations actions
export const REQUEST_FETCH_ORGANIZATIONS = 'REQUEST_FETCH_ORGANIZATIONS'
export const SUCCESS_FETCH_ORGANIZATIONS = 'SUCCESS_FETCH_ORGANIZATIONS'
export const FAILURE_FETCH_ORGANIZATIONS = 'FAILURE_FETCH_ORGANIZATIONS'


// Match actions
export const ADD_MATCH = 'ADD_MATCH'
export const UPDATE_MATCH = 'UPDATE_MATCH'
export const DELETE_MATCH = 'DELETE_MATCH'
export const SHOW_MATCH_REQUEST = 'SHOW_MATCH_REQUEST'
export const SHOW_MATCH_SUCCESS = 'SHOW_MATCH_SUCCESS'
export const SHOW_MATCH_FAILURE = 'SHOW_MATCH_FAILURE'
