// Auth actions
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE'
export const AUTH_LOAD = 'AUTH_LOAD'
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS'
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL'

// Mobilization actions
export const FETCH_MOBILIZATIONS = 'FETCH_MOBILIZATIONS'
export const EDIT_MOBILIZATION = 'EDIT_MOBILIZATION'
export const ADD_MOBILIZATION = 'ADD_MOBILIZATION'

// Widget actions
export const FETCH_WIDGETS = 'FETCH_WIDGETS'
export const EDIT_WIDGET = 'EDIT_WIDGET'

// Block actions
export const FETCH_BLOCKS = 'FETCH_BLOCKS'
export const EDIT_BLOCK = 'EDIT_BLOCK'
export const REMOVE_BLOCK = 'REMOVE_BLOCK'
export const MOVE_BLOCK_UP = 'MOVE_BLOCK_UP'
export const MOVE_BLOCK_DOWN = 'MOVE_BLOCK_DOWN'

// Form entries actions
export const ADD_FORM_ENTRY = 'ADD_FORM_ENTRY'
