export const FETCH = 'community/FETCH'

export const FETCH_SUCCESS = 'community/FETCH_SUCCESS'

export const FETCH_FAIL = 'community/FETCH_FAIL'

export const ADD = 'community/ADD'

export const EDIT = 'community/EDIT'

export const SELECT = 'community/SELECT'

export const UNSET = 'community/UNSET'

export const FETCH_DNS_HOSTED_ZONES_REQUEST = 'FETCH_DNS_HOSTED_ZONES_REQUEST'
export const FETCH_DNS_HOSTED_ZONES_SUCCESS = 'FETCH_DNS_HOSTED_ZONES_SUCCESS'
export const FETCH_DNS_HOSTED_ZONES_FAILURE = 'FETCH_DNS_HOSTED_ZONES_FAILURE'

export const ADD_DNS_HOSTED_ZONE_REQUEST = 'ADD_DNS_HOSTED_ZONE_REQUEST'
export const ADD_DNS_HOSTED_ZONE_SUCCESS = 'ADD_DNS_HOSTED_ZONE_SUCCESS'
export const ADD_DNS_HOSTED_ZONE_FAILURE = 'ADD_DNS_HOSTED_ZONE_FAILURE'

export const FETCH_DNS_RECORDS_REQUEST = 'FETCH_DNS_RECORDS_REQUEST'
export const FETCH_DNS_RECORDS_SUCCESS = 'FETCH_DNS_RECORDS_SUCCESS'
export const FETCH_DNS_RECORDS_FAILURE = 'FETCH_DNS_RECORDS_FAILURE'

export const DELETE_DNS_HOSTED_ZONE_REQUEST = 'DELETE_DNS_HOSTED_ZONE_REQUEST'
export const DELETE_DNS_HOSTED_ZONE_SUCCESS = 'DELETE_DNS_HOSTED_ZONE_SUCCESS'
export const DELETE_DNS_HOSTED_ZONE_FAILURE = 'DELETE_DNS_HOSTED_ZONE_FAILURE'
