export const LOAD_SUCCESS = 'authenticate/LOAD_SUCCESS'

export const SIGN_REQUEST = 'authenticate/SIGN_REQUEST'
export const SIGN_SUCCESS = 'authenticate/SIGN_SUCCESS'
export const SIGN_FAILURE = 'authenticate/SIGN_FAILURE'

export const UPDATE_USER_REQUEST = 'account/UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'account/UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'account/UPDATE_USER_FAILURE'

export const ADD_USER_REQUEST = 'account/ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'account/ADD_USER_SUCCESS'
export const ADD_USER_FAILURE = 'account/ADD_USER_FAILURE'

export const ASYNC_RETRIEVE_PASSWORD_REQUEST = 'ASYNC_RETRIEVE_PASSWORD_REQUEST'
export const ASYNC_RETRIEVE_PASSWORD_SUCCESS = 'ASYNC_RETRIEVE_PASSWORD_SUCCESS'
export const ASYNC_RETRIEVE_PASSWORD_FAILURE = 'ASYNC_RETRIEVE_PASSWORD_FAILURE'
