export const FETCH_WIDGETS_REQUEST = 'FETCH_WIDGETS_REQUEST'
export const FETCH_WIDGETS_SUCCESS = 'FETCH_WIDGETS_SUCCESS'
export const FETCH_WIDGETS_FAILURE = 'FETCH_WIDGETS_FAILURE'

export const UPDATE_WIDGET_REQUEST = 'UPDATE_WIDGET_REQUEST'
export const UPDATE_WIDGET_SUCCESS = 'UPDATE_WIDGET_SUCCESS'
export const UPDATE_WIDGET_FAILURE = 'UPDATE_WIDGET_FAILURE'

export const FETCH_BLOCKS_REQUEST = 'FETCH_BLOCKS_REQUEST'
export const FETCH_BLOCKS_SUCCESS = 'FETCH_BLOCKS_SUCCESS'
export const FETCH_BLOCKS_FAILURE = 'FETCH_BLOCKS_FAILURE'

export const UPDATE_BLOCK_REQUEST = 'UPDATE_BLOCK_REQUEST'
export const UPDATE_BLOCK_SUCCESS = 'UPDATE_BLOCK_SUCCESS'
export const UPDATE_BLOCK_FAILURE = 'UPDATE_BLOCK_FAILURE'

export const MOUSE_OVER = 'MOUSE_OVER'
export const MOUSE_OUT = 'MOUSE_OUT'

export const TURN_ON_EDITION = 'TURN_ON_EDITION'
export const TURN_OFF_EDITION = 'TURN_OFF_EDITION'

export const MOVE_BLOCK_UP = 'MOVE_BLOCK_UP'
export const MOVE_BLOCK_DOWN = 'MOVE_BLOCK_DOWN'

export const LOADING_FILE = 'LOADING_FILE'
export const FINISH_LOADING_FILE = 'FINISH_LOADING_FILE'
