export const FETCH_WIDGETS_REQUEST = 'FETCH_WIDGETS_REQUEST'
export const FETCH_WIDGETS_SUCCESS = 'FETCH_WIDGETS_SUCCESS'
export const FETCH_WIDGETS_FAILURE = 'FETCH_WIDGETS_FAILURE'

export const UPDATE_WIDGET_REQUEST = 'UPDATE_WIDGET_REQUEST'
export const UPDATE_WIDGET_SUCCESS = 'UPDATE_WIDGET_SUCCESS'
export const UPDATE_WIDGET_FAILURE = 'UPDATE_WIDGET_FAILURE'

export const WIDGET_MOUSE_OVER = 'WIDGET_MOUSE_OVER'
export const WIDGET_MOUSE_OUT = 'WIDGET_MOUSE_OUT'

export const MOUSE_OVER = 'MOUSE_OVER'
export const MOUSE_OUT = 'MOUSE_OUT'

export const TURN_ON_EDITION_MODE = 'TURN_ON_EDITION_MODE'
export const TURN_OFF_EDITION_MODE = 'TURN_OFF_EDITION_MODE'
