export const ROOT_URL = 'http://localhost:1337/api'

export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR'
export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'

export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR'
export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOAD_DASHBOARD_ERROR = 'LOAD_DASHBOARD_ERROR'
export const LOAD_DASHBOARD_REQUEST = 'LOAD_DASHBOARD_REQUEST'
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS'

export const LOAD_FB_EVENT_REQUEST = 'LOAD_FB_EVENT_REQUEST'
export const LOAD_FB_EVENT_SUCCESS = 'LOAD_FB_EVENT_SUCCESS'
export const LOAD_FB_EVENT_ERROR = 'LOAD_FB_EVENT_ERROR'

export const LOAD_ACCOUNT_REQUEST = 'LOAD_ACCOUNT_REQUEST'
export const LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS'
export const LOAD_ACCOUNT_ERROR = 'LOAD_ACCOUNT_ERROR'

export const LOAD_EVENT_REQUEST = 'LOAD_EVENT_REQUEST'
export const LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS'
export const LOAD_EVENT_ERROR = 'LOAD_EVENT_ERROR'

export const LOGOUT = 'LOGOUT'
