export const FETCH_WIDGETS_REQUEST = 'FETCH_WIDGETS_REQUEST'
export const FETCH_WIDGETS_SUCCESS = 'FETCH_WIDGETS_SUCCESS'
export const FETCH_WIDGETS_FAILURE = 'FETCH_WIDGETS_FAILURE'

export const UPDATE_WIDGET_REQUEST = 'UPDATE_WIDGET_REQUEST'
export const UPDATE_WIDGET_SUCCESS = 'UPDATE_WIDGET_SUCCESS'
export const UPDATE_WIDGET_FAILURE = 'UPDATE_WIDGET_FAILURE'
