export const REQUEST_ASYNC_WIDGET_UPDATE = 'REQUEST_ASYNC_WIDGET_UPDATE'
export const SUCCESS_ASYNC_WIDGET_UPDATE = 'SUCCESS_ASYNC_WIDGET_UPDATE'
export const FAILURE_ASYNC_WIDGET_UPDATE = 'FAILURE_ASYNC_WIDGET_UPDATE'

export const REQUEST_ASYNC_WIDGET_FETCH = 'REQUEST_ASYNC_WIDGET_FETCH'
export const SUCCESS_ASYNC_WIDGET_FETCH = 'SUCCESS_ASYNC_WIDGET_FETCH'
export const FAILURE_ASYNC_WIDGET_FETCH = 'FAILURE_ASYNC_WIDGET_FETCH'

export const REQUEST_ASYNC_WIDGET_SELECT = 'REQUEST_ASYNC_WIDGET_SELECT'
export const SUCCESS_ASYNC_WIDGET_SELECT = 'SUCCESS_ASYNC_WIDGET_SELECT'
export const FAILURE_ASYNC_WIDGET_SELECT = 'FAILURE_ASYNC_WIDGET_SELECT'
