export const REQUEST_ASYNC_WIDGET_UPDATE = 'REQUEST_ASYNC_WIDGET_UPDATE'
export const SUCCESS_ASYNC_WIDGET_UPDATE = 'SUCCESS_ASYNC_WIDGET_UPDATE'
export const FAILURE_ASYNC_WIDGET_UPDATE = 'FAILURE_ASYNC_WIDGET_UPDATE'

export const REQUEST_ASYNC_WIDGET_FETCH = 'REQUEST_ASYNC_WIDGET_FETCH'
export const SUCCESS_ASYNC_WIDGET_FETCH = 'SUCCESS_ASYNC_WIDGET_FETCH'
export const FAILURE_ASYNC_WIDGET_FETCH = 'FAILURE_ASYNC_WIDGET_FETCH'

export const REQUEST_ASYNC_WIDGET_SELECT = 'REQUEST_ASYNC_WIDGET_SELECT'
export const SUCCESS_ASYNC_WIDGET_SELECT = 'SUCCESS_ASYNC_WIDGET_SELECT'
export const FAILURE_ASYNC_WIDGET_SELECT = 'FAILURE_ASYNC_WIDGET_SELECT'

export const EXPORT_DATACLIP_REQUEST = 'EXPORT_DATACLIP_REQUEST'
export const EXPORT_DATACLIP_SUCCESS = 'EXPORT_DATACLIP_SUCCESS'
export const EXPORT_DATACLIP_FAILURE = 'EXPORT_DATACLIP_FAILURE'
export const EXPORT_DATACLIP_NO_DATA_FOUND = 'EXPORT_DATACLIP_NO_DATA_FOUND'
export const EXPORT_DATACLIP_FORCE_DOWNLOAD = 'EXPORT_DATACLIP_FORCE_DOWNLOAD'
export const EXPORT_DATACLIP_MOUNT = 'EXPORT_DATACLIP_MOUNT'

export const SET_WIDGET_LIST = 'SET_WIDGET_LIST'
