name: Reusable build for apps
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      REACT_APP_ENVIRONMENT:
        required: true
      REACT_APP_DOMAIN_IMAGINARY:
        required: true
      REACT_APP_DOMAIN_ACCOUNTS:
        required: true
      REACT_APP_DOMAIN_ADMIN:
        required: true
      REACT_APP_DOMAIN_ADMIN_CANARY:
        required: true
      REACT_APP_DOMAIN_API_GRAPHQL:
        required: true
      REACT_APP_DOMAIN_BOT:
        required: true
      REACT_APP_DOMAIN_BETA:
        required: true
      REACT_APP_AWS_BUCKET:
        required: true
      REACT_APP_LOGIN_URL:
        required: true
      REACT_APP_DOMAIN_REDES:
        required: true
      REACT_APP_UPLOADS_URL:
        required: true
      REACT_APP_ZENDESK_ORGANIZATIONS_LAWYER:
        required: true
      REACT_APP_ZENDESK_ORGANIZATIONS_INDIVIDUAL:
        required: true
      REACT_APP_ZENDESK_ORGANIZATIONS_THERAPIST:
        required: true
      REACT_APP_DOMAIN_PUBLIC:
        required: true
      REACT_APP_DOMAIN_API_ACTIVISTS:
        required: true
      REACT_APP_DOMAIN_API_REST:
        required: true
      AWS_ROUTE_IP:
        required: true
      HOTJAR_ID:
        required: true
      HOTJAR_SV:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: nossas/bonde-clients

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            SKIP_PREFLIGHT_CHECK=true
            "REACT_APP_ENVIRONMENT=${{ secrets.REACT_APP_ENVIRONMENT }}"
            "REACT_APP_DOMAIN_IMAGINARY=${{ secrets.REACT_APP_DOMAIN_IMAGINARY }}"
            "REACT_APP_DOMAIN_ACCOUNTS=${{ secrets.REACT_APP_DOMAIN_ACCOUNTS }}"
            "REACT_APP_DOMAIN_ADMIN=${{ secrets.REACT_APP_DOMAIN_ADMIN }}"
            "REACT_APP_DOMAIN_ADMIN_CANARY=${{ secrets.REACT_APP_DOMAIN_ADMIN_CANARY }}"
            "REACT_APP_HASURA_API_URL=${{ secrets.REACT_APP_DOMAIN_API_GRAPHQL }}"
            "REACT_APP_DOMAIN_BOT=${{ secrets.REACT_APP_DOMAIN_BOT }}"
            "REACT_APP_DOMAIN_BETA=${{ secrets.REACT_APP_DOMAIN_BETA }}"
            "REACT_APP_AWS_BUCKET=${{ secrets.REACT_APP_AWS_BUCKET }}"
            "REACT_APP_LOGIN_URL=${{ secrets.REACT_APP_LOGIN_URL }}"
            "REACT_APP_DOMAIN_REDES=${{ secrets.REACT_APP_DOMAIN_REDES }}"
            "REACT_APP_UPLOADS_URL=${{ secrets.REACT_APP_UPLOADS_URL }}"
            "REACT_APP_ZENDESK_ORGANIZATIONS_LAWYER=${{ secrets.REACT_APP_ZENDESK_ORGANIZATIONS_LAWYER }}"
            "REACT_APP_ZENDESK_ORGANIZATIONS_INDIVIDUAL=${{ secrets.REACT_APP_ZENDESK_ORGANIZATIONS_INDIVIDUAL }}"
            "REACT_APP_ZENDESK_ORGANIZATIONS_THERAPIST=${{ secrets.REACT_APP_ZENDESK_ORGANIZATIONS_THERAPIST }}"
            "REACT_APP_DOMAIN_PUBLIC=${{ secrets.REACT_APP_DOMAIN_PUBLIC }}"
            "REACT_APP_DOMAIN_API_ACTIVISTS=${{ secrets.REACT_APP_DOMAIN_API_ACTIVISTS }}"
            "REACT_APP_DOMAIN_API_GRAPHQL=${{ secrets.REACT_APP_DOMAIN_API_GRAPHQL }}"
            "REACT_APP_DOMAIN_API_REST=${{ secrets.REACT_APP_DOMAIN_API_REST }}"
            "REACT_APP_AWS_ROUTE_IP=${{ secrets.AWS_ROUTE_IP }}"
            "REACT_APP_HOTJAR_ID=${{ secrets.HOTJAR_ID }}"
            "REACT_APP_HOTJAR_SV=${{ secrets.HOTJAR_SV }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}