name: Continuous Integration for clients
on:
  push:
    branches:
      - "release/*"
      - "feature/*"
      - "hotfix/*"

jobs:
  build:
    name: Build clients app to staging.bonde.org
    uses: ./.github/workflows/build-clients.yml
    with:
      environment: staging
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      REACT_APP_ENVIRONMENT: staging
      REACT_APP_DOMAIN_IMAGINARY: https://imaginary.staging.bonde.org
      REACT_APP_DOMAIN_ACCOUNTS: https://accounts.staging.bonde.org
      REACT_APP_DOMAIN_ADMIN: https://app.staging.bonde.org
      REACT_APP_DOMAIN_ADMIN_CANARY: https://admin-canary.staging.bonde.org
      REACT_APP_DOMAIN_BOT: https://chatbot.staging.bonde.org
      REACT_APP_DOMAIN_BETA: https://beta.staging.bonde.org
      REACT_APP_AWS_BUCKET: bonde-assets-staging
      REACT_APP_LOGIN_URL: https://accounts.staging.bonde.org/login
      REACT_APP_DOMAIN_REDES: https://redes.staging.bonde.org
      REACT_APP_UPLOADS_URL: https://api-rest.staging.bonde.org/uploads
      REACT_APP_ZENDESK_ORGANIZATIONS_LAWYER: '360269610652'
      REACT_APP_ZENDESK_ORGANIZATIONS_INDIVIDUAL: '360273031591'
      REACT_APP_ZENDESK_ORGANIZATIONS_THERAPIST: '360282119532'
      REACT_APP_DOMAIN_PUBLIC: staging.bonde.org
      REACT_APP_DOMAIN_API_ACTIVISTS: https://api-graphql.staging.bonde.org/v1/graphql
      REACT_APP_DOMAIN_API_GRAPHQL: https://api-graphql.staging.bonde.org/v1/graphql
      REACT_APP_DOMAIN_API_REST: https://api-rest.staging.bonde.org
      AWS_ROUTE_IP: '127.0.0.1'
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}
      HOTJAR_SV: ${{ secrets.HOTJAR_SV }}